apiVersion: apps/v1

kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          name: wordpress
          resources:
                requests:
                  memory: "500Mi"
                  cpu: "100m"
                limits:
                  memory: "1024Mi"
                  cpu: "300m"
          env:
          - name: WORDPRESS_DB_HOST
            value: "db.database.io"
          - name: WORDPRESS_DB_NAME
            value: "extraweb"
          - name: WORDPRESS_DB_USER
            value: "extraadmin"
          - name: WORDPRESS_DB_PASSWORD
            value: "1234"
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-volumeclaim
      dnsPolicy: "None" 
      dnsConfig:
        nameservers:
          - 211.100.2.63
